### PR TITLE
Change Export Paid Commission to header

### PR DESCRIPTION
**Pull request by chriscct7**
It doesn't make much sense as a p. Looks out of place like this: http://screencloud.net/v/e82K

### CODE REVIEW

**Comment by chriscct7** [comment]
This will almost certainly merge conflict with my other PR, so I'd merge this one 2nd just in case.

**Comment by pippinsplugins** [comment]
@chriscct7 Can you please update the PR to merge cleanly?

**Comment by cklosowski** [comment]
@pippinsplugins updated to fix merge conflict

**Comment by pippinsplugins** [comment]
Looks good.

**Pull request merged**
