### PR TITLE
Make rates arguments filterable for easy extension

### PR DESCRIPTION
**Pull request by davidsherlock**
As per my previous action hook submissions, if the $rates array is filterable it will be easy to extend the meta box with new fields, which will work in tandem with the hooks and parameters I submitted earlier today.

### CODE REVIEW

**Comment by pippinsplugins** [comment]
@davidsherlock could you please show an example of new fields you'd like to add through this?

**Comment by davidsherlock** [comment]
I already have everything working using this commit, here is the function I am using:

```
        public function filter_rates_query_args( $rates, $users, $i ) {
          global $post;

          $meta       = get_post_meta( $post->ID, '_edd_commission_threshold_settings', true );
          $thresholds = isset( $meta['threshold'] ) ? $meta['threshold'] : '';
        	$thresholds = ! empty( $thresholds ) ? array_map( 'trim', explode( ',', $thresholds ) ) : array();
        	$rates['threshold'] = array_key_exists( $i, $thresholds ) ? $thresholds[ $i ] : '';

          return $rates;
        }
```

Effectively, I forked and modified the save function for the commission `user_ids` and `amounts` and saved the same array out for user ids and thresholds. This means everything matches up perfectly when both save.

As per this screenshot:

screenshot 2018-01-05 20 00 36

**Comment by davidsherlock** [comment]
@pippinsplugins, I have finished my plugin and can share it with you if you want to check it out (or give you access to the repo). I will release it if this filter can be added into the next commission release.

**Comment by davidsherlock** [comment]
@pippinsplugins, here is the repo for my next free extension: https://github.com/davidsherlock/edd-commission-thresholds

If this filter can be added in the next Commissions point release, I can release this plugin.

**Pull request merged**
