### PR TITLE
Add strict type casting to eddc_get_recipient_rate() to ensure the pr…

### PR DESCRIPTION
**Pull request by pippinsplugins**
…oper rate is always returned. Must properly support 0 rates. #120

### CODE REVIEW

**Comment by cklosowski** [comment]
These aren't going to pass until WordPress core adds the unit tests for the `4.4.2` release it's failing downloading those:
`svn: URL 'https://develop.svn.wordpress.org/tags/4.4.2/tests/phpunit/includes' doesn't exist`

**Comment by cklosowski** [comment]
thoughts @pippinsplugins ? every other part of the matrix passes

**Comment by pippinsplugins** [comment]
@cklosowski Only the 4.4.2 tests are failing (due to core not being updated yet apparently). I say it's safe to merge and deploy.

**Comment by cklosowski** [comment]
Agreed, merging so we can start pushing this out.

**Pull request merged**
